"use client";
import {useEffect,useState,useSyncExternalStore} from 'react';
import {BookOpen,FolderOpen,RefreshCw} from 'lucide-react';
import AppShell from '@/components/app-shell';
import RosterEditor from '@/components/roster-editor';
import DataCard from '@/components/data-card';
import UnitImage from '@/components/unit-image';
import {useCatalogue} from '@/lib/use-catalogue';
import {emptyRoster,validRoster,type ArmyRoster} from '@/lib/roster';
import {libraryCard,keepCard} from '@/lib/game-card-library';
import {subscribeHydration,clientHydrated,serverHydrated} from '@/lib/hydration';
import {factionStyle} from '@/lib/factions';
import type {UnitCard} from '@/lib/types';
const PREFIX='field-game-cards-11:';
type Saved={roster:ArmyRoster;used:string[]};
function read(faction:string):Saved{try{const d=JSON.parse(localStorage.getItem(PREFIX+faction)||'null');if(d&&validRoster(d.roster))return {roster:d.roster,used:Array.isArray(d.used)?d.used.filter((id:unknown)=>typeof id==='string').slice(0,500):[]};}catch{}return {roster:emptyRoster(),used:[]};}
export default function GameCards(){const ready=useSyncExternalStore(subscribeHydration,clientHydrated,serverHydrated);return <AppShell title="Game Data Cards">{ready?<Library/>:<p>Loading saved armies…</p>}</AppShell>;}
function Library(){
 const {units,error}=useCatalogue();const [faction,setFaction]=useState(()=>{try{return localStorage.getItem(PREFIX+'last-army')||'';}catch{return '';}});
 const [saved,setSaved]=useState(()=>read(faction)),[editing,setEditing]=useState(false),[playing,setPlaying]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[storageError,setStorageError]=useState('');
 const [cards,setCards]=useState<Record<string,UnitCard>>({}),[selected,setSelected]=useState(''),[failed,setFailed]=useState<string[]>([]);
 const factionUnits=units.filter(u=>u.faction===faction),ids=[...new Set(saved.roster.entries.filter(e=>e.count>0&&factionUnits.some(u=>u.id===e.unitId)).map(e=>e.unitId))];
 const factions=[...new Set(units.map(u=>u.faction))].sort((a,b)=>{const order=['Adeptus Custodes','Genestealer Cults'];return (order.includes(a)?order.indexOf(a):-1)===-1?(order.includes(b)?1:a.localeCompare(b)):(order.includes(b)?order.indexOf(a)-order.indexOf(b):-1);});
 useEffect(()=>{if(!faction)return;try{localStorage.setItem(PREFIX+faction,JSON.stringify(saved));localStorage.setItem(PREFIX+'last-army',faction);setStorageError('');}catch{setStorageError('This browser could not save the army selection. It remains available while this page is open.');}},[faction,saved]);
 function chooseFaction(value:string){setFaction(value);setSaved(read(value));setCards({});setSelected('');setFailed([]);setStatus('');}
 async function prepare(){if(!ids.length)return;setBusy(true);setFailed([]);const result:Record<string,UnitCard>={},missing:string[]=[];let done=0,unsaved=false;const queue=[...ids];await Promise.all(Array.from({length:Math.min(3,queue.length)},async()=>{while(queue.length){const id=queue.shift()!;try{const card=await libraryCard(id);result[id]={...card,image:units.find(u=>u.id===id)?.image};try{await keepCard(card);}catch{unsaved=true;}}catch{missing.push(id);}setStatus(`Preparing cards ${++done}/${ids.length}`);}}));setCards(result);setFailed(missing);setSelected(ids.find(id=>result[id])||ids[0]);setSaved(old=>({...old,used:[...new Set([...ids,...old.used])]}));setBusy(false);setPlaying(true);setStatus(missing.length?`${missing.length} cards could not load. Retry them when connected.`:unsaved?'Cards ready. This browser could not retain all cards for another session.':'Cards ready · saved on this device.');}
 async function refresh(id:string){setBusy(true);setStatus('Refreshing card…');try{const response=await fetch('/api/card?id='+encodeURIComponent(id)+'&refresh=1');const card=await response.json() as UnitCard&{error?:string};if(!response.ok)throw Error(card.error||'Card unavailable');setCards(old=>({...old,[id]:{...card,image:units.find(u=>u.id===id)?.image}}));setFailed(old=>old.filter(v=>v!==id));try{await keepCard(card);setStatus(card.warning||'Card refreshed and saved.');}catch{setStatus('Card refreshed, but could not be saved for another session.');}}catch(e){setStatus(e instanceof Error?e.message:'Refresh failed.');}finally{setBusy(false);}}
 const card=cards[selected];
 return <div className={`game-card-page ${playing?'cards-playing':''}`}><header className="stage-heading"><h1>{playing?faction+' · Game Data Cards':'Prepare your game cards'}</h1>{playing&&<button className="action" disabled={busy} onClick={()=>setPlaying(false)}><FolderOpen size={22}/>Edit army</button>}</header>{!playing?<><section className="game-card-setup"><label>Main army<select value={faction} disabled={busy} onChange={e=>chooseFaction(e.target.value)}><option value="">Choose an army…</option>{factions.map(f=><option key={f}>{f}</option>)}</select></label><p>Build your selection or import a Warhammer app army export. Previously used units appear first.</p><div className="stage-actions"><button className="action" disabled={!faction||busy} onClick={()=>setEditing(true)}><FolderOpen/>Build / import army</button><button className="action primary" disabled={!ids.length||busy||saved.roster.mode==='none'} onClick={()=>void prepare()}><BookOpen/>{busy?'Preparing…':`Open ${ids.length} data cards`}</button></div><div className="game-card-selected">{ids.map(id=>{const u=units.find(u=>u.id===id)!;return <div className="faction-tile" style={factionStyle(u.faction)} key={id}><UnitImage unit={u}/><strong>{u.name}</strong></div>;})}</div></section><p className="setup-note">Army selections and downloaded cards are saved in this browser on this device. GitHub synchronises the app, not your personal saved armies.</p></>:<><nav className="game-card-tabs" aria-label="Selected army data cards">{ids.map(id=>{const u=units.find(u=>u.id===id)!;return <button className="faction-tile" key={id} style={factionStyle(u.faction)} aria-pressed={selected===id} onClick={()=>setSelected(id)}><UnitImage unit={u}/><span>{u.name}{failed.includes(id)&&<small>Retry needed</small>}</span></button>;})}</nav>{card?<><DataCard card={card}/><details className="game-card-source"><summary>Source & refresh · {new Date(card.source.retrievedAt).toLocaleDateString()}</summary><a href={card.source.url} target="_blank" rel="noreferrer">Wahapedia · {card.source.edition}th edition</a><button className="action" disabled={busy} onClick={()=>void refresh(selected)}><RefreshCw size={20}/>Refresh this card</button>{card.image&&<a href={card.image.source} target="_blank" rel="noreferrer">Photo: {card.image.credit}</a>}</details></>:<section className="empty-card"><h2>This card could not load</h2><button className="action" disabled={busy} onClick={()=>void refresh(selected)}>Retry card</button></section>}</>}{(status||storageError||error)&&<p className="library-status" role="status">{storageError||error||status}</p>}{editing&&<RosterEditor name={faction} units={factionUnits} value={saved.roster} preferredIds={saved.used} cardsOnly onChange={roster=>setSaved(old=>({...old,roster}))} onClose={()=>setEditing(false)}/>}</div>;
}
