"use client";
import {useEffect,useRef,useMemo,useState} from 'react';
import {ClipboardPaste,ListPlus,Minus,Plus,X} from 'lucide-react';
import type {CatalogueUnit} from '@/lib/types';
import {emptyRoster,parseArmyExport,rosterTotal,type ArmyRoster,type ImportRow,type RosterEntry} from '@/lib/roster';
import {factionStyle} from '@/lib/factions';
import UnitImage from './unit-image';
export default function RosterEditor({units,value,onChange,onClose,name}:{units:CatalogueUnit[];value?:ArmyRoster;onChange:(r:ArmyRoster)=>void;onClose:()=>void;name:string}){
 const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{const element=dialog.current;element?.showModal();return()=>element?.close();},[]);
 const roster=value||emptyRoster();const [query,setQuery]=useState(''),[rows,setRows]=useState<ImportRow[]|null>(null),[error,setError]=useState(''),[mapping,setMapping]=useState<number|null>(null),[ignored,setIgnored]=useState<number[]>([]);
 const total=rosterTotal(roster.entries,units),selected=roster.entries.reduce((n,e)=>n+e.count,0);
 const filtered=useMemo(()=>units.filter(u=>u.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name)),[units,query]);
 function update(entries:RosterEntry[]){onChange({...roster,entries});}
 function count(unitId:string,models:number,delta:number,option?:string){const old=roster.entries.find(e=>e.unitId===unitId&&e.models===models&&e.option===option);update([...roster.entries.filter(e=>e!==old),{unitId,models,option,count:Math.max(0,Math.min(30,(old?.count||0)+delta))}].filter(e=>e.count));}
 function parse(){try{const parsed=parseArmyExport(roster.text,units);if(!parsed.length)throw Error('No unit headings found. Paste the text army export, including unit names and points.');setRows(parsed);setIgnored([]);setError('');}catch(e){setError((e as Error).message);}}
 const imported=rows?.flatMap((r,i)=>ignored.includes(i)?[]:[{unitId:r.unitId,models:r.models,option:r.option,count:1}])||[];
 const valid=!!rows?.length&&imported.length>0&&imported.every(e=>units.find(u=>u.id===e.unitId)?.sizes?.some(s=>s.models===e.models));
 const preview=rosterTotal(imported,units);
 function choose(row:number,change:Partial<ImportRow>){setRows(old=>old!.map((r,i)=>i===row?{...r,...change}:r));}
 return <dialog ref={dialog} onCancel={e=>{e.preventDefault();onClose();}} className="roster-overlay" aria-label={`${name} army roster`} style={factionStyle(units[0]?.faction||'')}><header className="roster-heading"><div><h2>{name} · Army</h2><span aria-live="polite">{selected} units · {total.points} pts{total.unknown?' + unverified costs':''}</span></div><button className="action primary" onClick={onClose}>Done <X size={18}/></button></header><nav className="roster-modes" aria-label="Army selection method">{(['none','import','build'] as const).map(mode=><button className="action" aria-pressed={roster.mode===mode} key={mode} onClick={()=>{onChange({...roster,mode});setRows(null);}}>{mode==='none'?<Minus/>:mode==='import'?<ClipboardPaste/>:<ListPlus/>}{mode==='none'?'None':mode==='import'?'Import army':'Build / select army'}</button>)}</nav>
 {roster.mode==='none'?<p>No roster filter. Use voice, search and recent cards during the game. Your draft remains saved.</p>:<>{roster.mode==='import'&&<section className="import-panel"><label htmlFor="army-export">Paste Warhammer app army export · draft saved on this device</label><textarea id="army-export" maxLength={100000} value={roster.text} placeholder={'My army (1000 Points)\n\nCustodian Guard (170 Points)\n • 4x Custodian Guard\n   ◦ 4x Guardian spear'} onChange={e=>{onChange({...roster,text:e.target.value});setRows(null);}}/><button className="action primary" disabled={!roster.text.trim()} onClick={parse}>Review import →</button>{error&&<p role="alert">{error}</p>}
 <p className="setup-note">Pasting text keeps your current selected army until you choose Use reviewed army.</p>{rows&&<div className="import-review"><h3>Review {rows.length} units · {preview.points} pts{preview.unknown?' + unverified':''}</h3><p>Unit points use the dated 11th-edition source below. Enhancements, wargear choices and roster legality need checking at the table; the pasted text is preserved.</p>{rows.map((r,i)=>{const unit=units.find(u=>u.id===r.unitId);return <div key={i} className={`import-row ${ignored.includes(i)?'ignored':''}`}><div><strong>{r.name}</strong><span>Export: {r.exportPoints} pts · {r.models||'?'} models</span></div><button className="action" onClick={()=>{setMapping(mapping===i?null:i);setQuery('');}}>{unit?.name||'Match unit…'}</button><div className="size-options">{[...new Set(unit?.sizes?.map(s=>s.models)||[])].map(n=><button key={n} aria-pressed={r.models===n} onClick={()=>choose(i,{models:n})}>{n} models</button>)}</div><button className="action" aria-pressed={ignored.includes(i)} onClick={()=>setIgnored(old=>old.includes(i)?old.filter(n=>n!==i):[...old,i])}>{ignored.includes(i)?'Restore':'Exclude'}</button>{unit&&!unit.sizes?.some(s=>s.models===r.models)&&<span role="alert">Choose a supported model count.</span>}{mapping===i&&<div className="import-matches"><input aria-label="Find matching unit" value={query} onChange={e=>setQuery(e.target.value)}/>{filtered.map(u=><button key={u.id} className="action" onClick={()=>{choose(i,{unitId:u.id,models:u.sizes?.some(s=>s.models===r.models)?r.models:u.sizes?.[0]?.models||0});setMapping(null);setQuery('');}}>{u.name}</button>)}</div>}</div>;})}<button className="action primary" disabled={!valid} onClick={()=>{update(imported);setRows(null);setError('Imported roster saved. Review or adjust it in Build / select army.');}}>Use reviewed army{preview.unknown?' · some costs unverified':''} · replace selected units</button></div>}</section>}
 {roster.mode==='build'&&<><div className="roster-filter"><input aria-label="Filter available units" placeholder="Filter units…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{filtered.length} available units</span></div><div className="roster-list">{filtered.map(u=>{const sizes=[...new Map((u.sizes||[]).map(s=>[s.label||String(s.models),s])).values()];return <article className="roster-unit" key={u.id} style={factionStyle(u.faction)}><UnitImage unit={u}/><div className="roster-unit-copy"><h3>{u.name}</h3><span>{u.faction}</span>{sizes.length?sizes.map(size=>{const models=size.models,option=size.label;const entry=roster.entries.find(e=>e.unitId===u.id&&e.models===models&&e.option===option);const costs=u.sizes!.filter(s=>s.models===models&&s.label===option);const prices=[...new Set(costs.map(s=>s.points))];return <div className="roster-size" key={option||models}><span><b>{option||`${models} model${models===1?'':'s'}`}</b> · {Math.min(...prices)}{prices.length>1?`–${Math.max(...prices)}`:''} pts</span><div className="stepper"><button aria-label={`Remove ${models}-model ${u.name} unit`} disabled={!entry?.count} onClick={()=>count(u.id,models,-1,option)}><Minus size={20}/></button><output aria-label={`${models}-model ${u.name} units`}>{entry?.count||0}</output><button aria-label={`Add ${models}-model ${u.name} unit`} disabled={(entry?.count||0)>=30} onClick={()=>count(u.id,models,1,option)}><Plus size={20}/></button></div></div>;}):<p>Model sizes / points unavailable · <a href={u.url} target="_blank" rel="noreferrer">Check source</a></p>}</div></article>;})}</div></>}
 <details className="roster-source"><summary>Points & image sources</summary><p>11th-edition points snapshot · {units.find(u=>u.pointsRetrievedAt)?.pointsRetrievedAt?.slice(0,10)||'Date unavailable'}. Repeated-unit price tiers are included in the total. Chapter / army-dependent prices remain unverified where the source gives alternatives. Enhancements and army legality are not included.</p>{roster.entries.map(e=>units.find(u=>u.id===e.unitId)).filter((u,i,list)=>u&&list.findIndex(v=>v?.id===u.id)===i).map(u=><p key={u!.id}><a href={u!.url} target="_blank" rel="noreferrer">{u!.name} · points</a>{u!.image&&<> · <a href={u!.image.source} target="_blank" rel="noreferrer">Photo: {u!.image.credit}</a></>}</p>)}</details></>}
 </dialog>;
}
