"use client";
import {useEffect,useRef,useState} from "react";
import {Mic,Square} from "lucide-react";
import type {CatalogueUnit,UnitCard} from "@/lib/types";
import {rankUnits} from "@/lib/search";
import {createSpeechRecognition,type SpeechSession} from "@/lib/speech";
import {loadCard} from "@/lib/card-loader";
import UnitImage from "@/components/unit-image";
import {rememberUnit,recentUnits} from "@/lib/recent-units";
import {factionStyle} from "@/lib/factions";
export default function UnitSearch({catalogue,onCard,onSearching,recentScope,pinned=[],disabled=false}:{catalogue:CatalogueUnit[];onCard:(card:UnitCard)=>void;onSearching?:()=>void;recentScope?:string;pinned?:string[];disabled?:boolean}){
 const [query,setQuery]=useState(''),[listening,setListening]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[choices,setChoices]=useState<CatalogueUnit[]>([]);
 const speech=useRef<SpeechSession|null>(null),input=useRef<HTMLInputElement>(null),request=useRef(0);
 useEffect(()=>()=>{request.current++;speech.current?.abort();},[]);
 async function open(unit:CatalogueUnit){const seq=++request.current;setBusy(true);onSearching?.();setChoices([]);setMessage('Opening '+unit.name+'…');try{const card={...unit,...await loadCard(unit.id),image:unit.image};if(seq===request.current){if(recentScope)rememberUnit(recentScope,card!.id);onCard(card!);setMessage(card!.warning||'');}}catch(e){if(seq===request.current)setMessage(e instanceof Error?e.message:'Lookup failed.');}finally{if(seq===request.current)setBusy(false);}}
 function lookup(text:string){setQuery(text);if(!text.trim())return;const ranked=rankUnits(text,catalogue);if(!ranked.length){setChoices([]);setMessage('No match in the available factions. Try a full unit name.');return;}if(ranked[0].score>=.86&&(!ranked[1]||ranked[0].score-ranked[1].score>.08))void open(ranked[0].unit);else{setChoices(ranked.slice(0,6).map(r=>r.unit));setMessage('Choose your unit.');}}
 function speak(){if(listening){speech.current?.stop();return;}speech.current?.abort();input.current?.blur();setQuery('');setChoices([]);setMessage('Starting microphone…');let heard=false;const session=createSpeechRecognition({onStart:()=>setListening(true),onAudioStart:()=>setMessage('Say a unit name.'),onTranscript:setQuery,onResult:text=>{heard=true;lookup(text);},onError:text=>{heard=true;setMessage(text);},onEnd:()=>{setListening(false);if(!heard)setMessage('No speech captured. Try again or type.');}});if(!session){setMessage('Speech is unavailable in this browser. Type a unit name.');return;}speech.current=session;try{setListening(true);session.start();}catch{setListening(false);setMessage('Check microphone permissions and try again.');}}
 const quick=[...new Map([...pinned.flatMap(id=>catalogue.filter(u=>u.id===id)),...(recentScope?recentUnits(recentScope,catalogue):[])].map(u=>[u.id,u])).values()];
 return <div className="unit-search"><button className="voice-button" disabled={disabled||busy||!catalogue.length} onClick={speak}>{listening?<Square size={20}/>:<Mic size={20}/>} {listening?'Finish listening':'Tap to speak'}</button><form className="search-box" onSubmit={e=>{e.preventDefault();lookup(query);}}><input ref={input} aria-label="Unit name" placeholder="Unit name…" value={query} onChange={e=>setQuery(e.target.value)} readOnly={listening} inputMode={listening?'none':'text'} onFocus={e=>{if(listening)e.currentTarget.blur();}}/><button disabled={disabled||busy||listening||!catalogue.length}>Find</button></form>{message&&<p role="status">{message}</p>}{quick.length>0&&<div className="recent-units" aria-label="Roster and previously used by this player">{quick.map(u=><button key={u.id} className="faction-tile" style={factionStyle(u.faction)} disabled={disabled||busy||listening} onClick={()=>void open(u)}><UnitImage unit={u}/><span>{u.name}</span></button>)}</div>}<div className="candidates">{choices.map(u=><button key={u.id} disabled={busy||listening||disabled} style={factionStyle(u.faction)} className="faction-tile" onClick={()=>void open(u)}><strong>{u.name}</strong><span>{u.faction}</span></button>)}</div></div>;
}
