import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parseArmyExport,rosterTotal,validRoster} from '../lib/roster.ts';
const units=JSON.parse(await readFile('data/catalogue.json','utf8'));
const guard=units.find(u=>u.id==='adeptus-custodes/Custodian-Guard');
assert.deepEqual(rosterTotal([{unitId:guard.id,models:4,count:4}],units),{points:690,unknown:0});
assert.deepEqual(rosterTotal([{unitId:guard.id,models:99,count:1}],units),{points:0,unknown:1});
const text=`My Army (1,000 Points)\nAdeptus Custodes\nLions of the Emperor\n\nCustodian Guard (170 Points)\n • 4x Custodian Guard\n   ◦ 4x Guardian spear\n\nCustodian Guard (215 Points)\n • 5x Custodian Guard\n   ◦ 5x Sentinel blade\n\nUnknown Hero (80 Points)\n • 1x Hero\n   ◦ 1x Sword\n\nExported with App Version: 1.2`;
const rows=parseArmyExport(text,units.filter(u=>u.faction==='Adeptus Custodes'));
assert.equal(rows.length,3);assert.deepEqual(rows.map(r=>r.models),[4,5,1]);assert.equal(rows[2].unitId,'');
assert.deepEqual(rosterTotal(rows.slice(0,2).map(r=>({...r,count:1})),units),{points:385,unknown:0});
assert.equal(parseArmyExport('Terminator Squad (160 Points)\n • 5x Terminator',units.filter(u=>u.faction==='Space Marines'))[0].unitId,'');
assert.throws(()=>parseArmyExport('x'.repeat(100001),units),/100,000/);
const draft={mode:'import',text,entries:[{unitId:guard.id,models:4,count:2}]};assert.ok(validRoster(JSON.parse(JSON.stringify(draft))));
assert.equal(validRoster({...draft,entries:[{unitId:guard.id,models:4,count:-1}]}),false);
assert.equal(validRoster({...draft,text:'x'.repeat(100001)}),false);
assert.ok(units.filter(u=>u.sizes?.length).length>=690);
assert.equal(units.find(u=>u.id==='space-marines/Terminator-Squad').sizes[0].points,160);
assert.equal(units.find(u=>u.id==='adeptus-custodes/Prosecutors').image,undefined);
assert.equal(units.find(u=>u.id==='necrons/Necron-Warriors').image,undefined);
assert.equal(units.filter(u=>u.image).length,4);
assert.ok(units.filter(u=>u.image).every(u=>u.image.kind==='miniature'&&['white','transparent'].includes(u.image.background)&&/^\d{4}-\d{2}-\d{2}$/.test(u.image.verifiedAt)));
assert.ok(units.find(u=>u.id==='adeptus-custodes/Custodian-Guard').image);
assert.ok(units.find(u=>u.id==='genestealer-cults/Kelermorph').image);
console.log('PASS: export parsing, model bullets vs wargear, unknown/ambiguous names, repeated-unit points tiers, invalid sizes, draft round-trip, and verified model-only images.');
import {clearWhiteBackdrop} from '../lib/unit-art.ts';
const pixels=new Uint8ClampedArray(5*5*4).fill(255);
for(let y=1;y<4;y++)for(let x=1;x<4;x++){if(x===2&&y===2)continue;const i=(y*5+x)*4;pixels[i]=pixels[i+1]=pixels[i+2]=20;}
assert.equal(clearWhiteBackdrop(pixels,5,5),16);assert.equal(pixels[3],0);assert.equal(pixels[(2*5+2)*4+3],255);assert.equal(pixels[(1*5+1)*4+3],255);
console.log('PASS: edge-connected white background removal preserves enclosed white armour and dark model details.');
const actual=parseArmyExport(await readFile('scripts/fixtures/army-export.txt','utf8'),units.filter(u=>u.faction==='Genestealer Cults'));
assert.equal(actual.length,7);assert.ok(actual.every(r=>r.unitId));assert.deepEqual(actual.map(r=>r.models),[1,1,1,5,5,5,1]);
assert.equal(actual.reduce((n,r)=>n+r.exportPoints,0),515);
const actualTotal=rosterTotal(actual.map(r=>({...r,count:1})),units);assert.equal(actualTotal.unknown,0);
console.log('PASS: supplied Warhammer v2.6.0 export: seven units, correct single-model characters/vehicle and squad counts; current source total',actualTotal.points,'pts.');
