import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {defaults,resolveAttack,woundTarget,lionsEligible} from '../lib/battle.ts';
import {parseCard} from '../lib/wahapedia.ts';
import {parseFactionRules} from '../lib/faction-rules.ts';
const cards=JSON.parse(await readFile('data/snapshots.json','utf8'));
const rules=JSON.parse(await readFile('data/faction-rules.json','utf8'));
const c=cards.find(c=>c.name==='Custodian Guard'),n=cards.find(c=>c.name==='Necron Warriors');
const knight=parseCard(await readFile('.sites-runtime/versus/knight.html','utf8'),{id:'imperial-knights/Knight-Paladin',name:'Knight Paladin',faction:'Imperial Knights',url:'https://wahapedia.ru/wh40k11ed/factions/imperial-knights/Knight-Paladin'});
assert.match(knight.invulnerableCondition,/against ranged attacks only/i);
const det=rules['Adeptus Custodes'].detachments.find(d=>d.name==='Lions of the Emperor');
const player={id:'0-0',team:0,name:'Player',faction:'Adeptus Custodes',ally:'',detachment:det.id};
const a={playerId:'0-0',card:c,profile:0},d={playerId:'1-0',card:n,profile:0},k={...d,card:knight};
const ranged=c.weapons.find(w=>w.name==='Guardian spear'&&w.kind==='ranged'),melee=c.weapons.find(w=>w.name==='Guardian spear'&&w.kind==='melee');
const run=(w=ranged,conditions={},def=d)=>resolveAttack(a,def,w,{...defaults,...conditions},player,rules['Adeptus Custodes']);
assert.deepEqual([woundTarget(10,5),woundTarget(6,5),woundTarget(5,5),woundTarget(3,5),woundTarget(2,5)],[2,3,4,5,6]);
assert.equal(run().hit,'2+');assert.equal(run(undefined,{cover:true}).hit,'3+');
assert.equal(run(undefined,{cover:true,plunging:true}).hit,'2+');
assert.equal(run({...ranged,keywords:['ignores cover']},{cover:true}).hit,'2+');
assert.equal(run({...ranged,skill:'N/A',keywords:['torrent']},{cover:true}).hit,'Automatic');
assert.equal(run(melee,{},k).invulnerable,'Not applicable');assert.equal(run(ranged,{},k).invulnerable,'5+');
assert.equal(run(undefined,{hit:4,wound:3,isolated:true}).hitMod,1);assert.equal(run(undefined,{hit:-5,wound:-4}).woundMod,-1);
assert.ok(lionsEligible(a,player,rules['Adeptus Custodes']));assert.ok(!lionsEligible({...a,card:{...c,keywords:'VEHICLE'}},player,rules['Adeptus Custodes']));
assert.ok(!lionsEligible({...a,card:{...c,faction:'Adeptus Mechanicus'}},player,rules['Adeptus Custodes']));
assert.ok(run(melee,{katah:'lethal'}).keywords.includes('Lethal Hits'));assert.ok(!run(ranged,{katah:'lethal'}).keywords.includes('Lethal Hits'));
assert.equal(run({...ranged,ap:'-6'},{}, {...d,card:{...n,invulnerableSave:''}}).armour,'No normal save');
assert.ok(Object.values(rules).every(r=>r.edition===11&&r.army.text.length>50&&r.detachments.length>0));
assert.ok(Object.values(rules).every(r=>!r.detachments.some(d=>/Boarding|Combat Patrol/i.test(d.name))));
assert.throws(()=>parseFactionRules('<html/>','Custodes','https://wahapedia.ru/wh40k11ed/'));
console.log('PASS: wound table, 11th-edition cover and plunging fire, Ignores Cover, Torrent, ranged-only saves, roll caps, Lions eligibility, melee-only Ka’tah, impossible saves, and eight faction rule packs.');
